Wdc 15
beginning-web-dev/bwd-site pull request #19
Opened 2022-04-14 01:35 UTC by Michael-Futral

Updating of JS, CSS, and HTML to make navigation bar respond to scrolling from top. At top of page navigation bar features will remain as original in develop. However, when screen width is larger than 992px and when scrolling from top: 

- Navbar will shrink slightly
- Navbar will change colors
- The brand name "Web Dev Coop" will shrink in font size
- Also added a transition time for the animation so it is not clunky
- When returning to top navigation bar will return to as original

Code additions:

1. "#mainNav" id to index.html 'nav' element on line #31. 
2. Addition of #mainNav syntax to attribute '@media only screen and (min-width: 992px)' in main.css
3.Addition of main.js event listener that adds 'navbar-shrink' class to elements with id='mainNav' when scrolling more than 0 on y axis. 
4. Addition of scripts element at end of index.js to pull in main.js.

2022-04-18 23:20 UTC, wojo1086 requested changes
Revert all unnecessary spacing changes.

2022-04-18 23:30 UTC, wojo1086 requested changes

2022-04-18 23:30 UTC, wojo1086 commented on js/main.js
> +    var navbarShrink = function () {
Use `let` not `var`

2022-04-20 21:14 UTC, Michael-Futral commented on js/main.js
> +    var navbarShrink = function () {
Changed var to let.

Also rearranged the few sections in main.js as close as I could to remember to what you did in the meeting monday.

2022-04-20 21:16 UTC, Michael-Futral commented
Prettier has been removed in index.html (doesn't look like it messed with main.css),  and moved  <scripts src="js/main.js defer> to the head from where it original was at on the bottom of the file.

2022-04-21 13:57 UTC, merged