Wdc 16- Services Completed
beginning-web-dev/bwd-site pull request #20
Opened 2022-04-15 16:48 UTC by oleend

Finished the Services Tim! Let me know if there is anything you want to change!

2022-04-20 17:44 UTC, wojo1086 requested changes
Please revert all the extra spacing changes. It's making it difficult to see what you actually changed in your code.

2022-04-20 17:44 UTC, wojo1086 commented on index.html
> +    />
Please revert this back to be on one line. Try not to change the layout of the existing code until we decide on a coding standard.

2022-04-20 17:44 UTC, wojo1086 commented on index.html
> +    />
Here too.

2022-04-20 17:44 UTC, wojo1086 commented on index.html
> +    <script
And here.

2022-04-20 17:44 UTC, wojo1086 commented on index.html
> +    <script
And here.

2022-04-21 22:06 UTC, oleend commented on index.html
> +    />
This looks different then what is shown in github? Its on one line on my editor

2022-04-21 22:07 UTC, oleend commented on index.html
> +    />
Guess i need that editor plugin

2022-04-21 22:13 UTC, oleend commented on index.html
> +    <script
I can now see what you see!

2022-04-21 22:13 UTC, oleend commented on index.html
> +    <script
Ready to pull!

2022-04-25 23:45 UTC, wojo1086 approved these changes

2022-04-25 23:46 UTC, merged